FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir --upgrade flask redis minio requests jsonpickle

COPY rest/rest-server.py /app/rest-server.py

EXPOSE 5000

CMD ["python", "/app/rest-server.py"]
