apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest
spec:
  progressDeadlineSeconds: 900
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rest
  replicas: 1
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
      - name: rest
        image: demucs-rest:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: MINIO_HOST
          value: "minio:9000"
        - name: MINIO_ACCESS_KEY
          value: "rootuser"
        - name: MINIO_SECRET_KEY
          value: "rootpass123"
        - name: MINIO_INPUT_BUCKET
          value: "queue"
        - name: MINIO_OUTPUT_BUCKET
          value: "output"
